:_basedir:
:_imagesdir: images/
:grid: cols
:notoc:
:notitle:
:metadata:

[[index]]

= Communication

== Communication

The Project obtains its strength from the communication of its members.
In order for members to easily communicate with each other, the Project
has a variety of mailing lists. These lists, with the exception of the
announcement lists, are not moderated and anybody is more than welcome
to join them. However, you must be subscribed to post to a list.

To reduce the bandwidth demands on everyone, mail should not contain
attachments. It is recommended that you place interesting material (such
as patches) either within the body of the message or provide a URL for
retrieval.

To join the mailing lists, see our xref:mail.adoc[Mailing List] page.

The Project's list fall into the categories below.


=== Announcement Lists

Announcement lists are very low traffic designed to communicate
important information, such as final releases of a subproject's code, to
a wide audience.


=== User Lists

User lists are for users of a product to converse about such things as
configuration and operating of the products of the Project.


=== Developer Lists

Developer lists are for the developers of the project. On these lists
suggestions and comments for code changes are discussed and action items
are raised and voted on. For the developer community, these lists are
the very center of the project where all the "action" is.


=== Commit Lists

The commit lists are where all cvs code commit messages are sent. All
committers are required to subscribe to this list so that they can stay
aware of changes to the repository.
